import pandas as pd
df=pd.read_csv('hospital_records.csv')
df=df.drop_duplicates()
df['Hospital_Bill']=df['Days_Admitted']*df['Daily_Charge']
bill_before_insurance=df['Hospital_Bill'].sum()
df['Insurance_Discount']=df['Hospital_Bill']*df['Insurance']/100
df['Final_Bill']=df['Hospital_Bill']-df['Insurance_Discount']
total_revenue=df['Final_Bill'].sum()
bill_avg=df['Final_Bill'].mean().round(2)
department_revenue=df.groupby('Department')['Final_Bill'].sum()
department_revenue_highest=department_revenue.idxmax()
department_avg=df.groupby('Department')['Final_Bill'].mean().round(2)
patient=df['Department'].value_counts()
doc=df['Doctor'].value_counts()
doc_max=doc.max()
doctor=doc[doc==doc_max]
doctor_revenue=df.groupby('Doctor')['Final_Bill'].sum()
avg_age_department=df.groupby('Department')['Age'].mean().round(2)
disease=df['Disease'].value_counts()
disease_max=disease.max()
common_disease=disease[disease==disease_max]
top_patient_bills=df.nlargest(5,'Final_Bill')
top_5_bills=top_patient_bills
top_discount=df.nlargest(1,'Insurance_Discount')
top_insurance_discount=top_discount
spending_above=bill_avg
spending_above_masks=spending_above<df['Final_Bill']
spending_above_avg=df.loc[spending_above_masks]
spending_below_masks=spending_above>df['Final_Bill']
spending_below_avg=df.loc[spending_below_masks]
print(df)
print("\n===========================CITY-CARE-HOSPITAL====================================\n")
print(f"\n1) Total bill before insurance :{bill_before_insurance}")
print(f"\n2) Average bill  :{bill_avg}")
print(f"\n3) Total bill after insurance:{total_revenue}")
print(f"\n4) Revenue of each department: \n{department_revenue}")
print(f"\n5) Highest revenue generated department: \n{department_revenue_highest}")
print(f"\n6) Average revenue of each department: \n{department_avg}")
print(f"\n7) Number of patient in each Department: \n{patient}")
print(f"\n8) Highest patient treated by doctor:\n {doctor}")
print(f"\n9) Highest revenue generated by doctors:\n{doctor_revenue}")
print(f"\n10)Average age in each Department: \n{avg_age_department}")
print(f"\n11)Most common disease:{common_disease}")
print(f"\n12)Top 5 Hospital Bills:\n{top_5_bills}")
print(f"\n13)Patient with highest discount:\n{top_insurance_discount}")
print(f"\n14)Patient spending above averages:\n{spending_above_avg}")
print(f"\n15)Patient spending below averages:\n{spending_below_avg}")
print("\n==========================================================================================")
df.to_csv('cleaned_hospital_records.csv',index=False)


















































































