import pandas as pd
df=pd.read_csv("sales_data.csv")
df=df.drop_duplicates()
df['Revenue']=df['Quantity']*df['Price']
df['Discount_Amount']=df['Revenue']*df['Discount']/100
df['Final_Revenue']=df['Revenue']-df['Discount_Amount']
total_revenue=(df['Final_Revenue'].sum().round(2))
avg_revenue=(df['Final_Revenue'].mean().round(2))
product_sales=df.groupby('Product')['Quantity'].sum()
top_5_revenue=(df.nlargest(5,'Final_Revenue'))
most_sold_products=product_sales.idxmax()
region_rev=df.groupby('Region')['Final_Revenue'].sum()
category_rev=df.groupby('Category')['Final_Revenue'].sum()
customer_rev=df.groupby('Customer')['Final_Revenue'].sum()
avg_discount=(df['Discount'].mean().round(2))
highest_discount_index=df['Discount_Amount'].idxmax()
highest_discount_order=df.loc[highest_discount_index]
category_product=df.groupby('Category')['Product'].value_counts()
top_3_cust=df.groupby('Customer')['Final_Revenue'].sum()
top_3_customer=top_3_cust.nlargest(3)
top_3_product=df.groupby('Product')['Quantity'].sum()
top_3_products=top_3_product.nlargest(3)
customer_sales=df.groupby('Customer')['Final_Revenue'].sum()
above_average=customer_sales.mean().round(2)
above_average_mask=customer_sales>above_average
above_average_revenue=customer_sales[above_average_mask]
below=customer_sales<above_average
below_average_revenue=customer_sales[below]
print(df.head())
print(f"\n1:Total revenue after discount:  {total_revenue}")
print(f"\n2:Average revenue : {avg_revenue}")
print(f"\n3:Most sold product:\n{most_sold_products}")
print(f"\n4:Top 5 products with highest revenue:\n{top_5_revenue}")
print(f"\n5:Revenue generated in each region:\n{region_rev}")
print(f"\n6:Category revenue:\n{category_rev}")
print(f"\n7:Revenue generated by customers:\n{customer_rev}")
print(f"\nAverage discount: {avg_discount}")
print(f"\n8:Highest discounted product:\n{highest_discount_order}")
print(f"\n9:Products sold in each category:\n{category_product}")
print(f"\n10:Top 3 customers:\n{top_3_customer}")
print(f"\n11:Top 3 products:\n{top_3_products}")
print(f"\n12:Customers spending above average revenue:\n{above_average_revenue}")
print(f"\n13:Customers spending below average revenue:\n{below_average_revenue}")
df.to_csv("Cleaned_sales_data.csv",index=False)